// =============================================================
//  NINETEEN84 — A C64 Demo
//  George Orwell's 1984 meets AI
//  Did we get the technology we were promised?
//  And at what cost?
//
//  Build:   oscar64 -tm=c64 -O2 nineteen84.c
//  Run:     x64sc.exe -autostart nineteen84.prg
// =============================================================

#include <c64/vic.h>
#include <c64/cia.h>
#include <c64/memmap.h>
#include "responses.h" // generated by: python convert.py responses.txt responses.h

// ---------------------------------------------------------------------------
// Hardware
// ---------------------------------------------------------------------------
#define SCREEN ((char *)0x0400)
#define COLORRAM ((char *)0xd800)

// VIC-II palette
#define BLACK 0
#define WHITE 1
#define RED 2
#define CYAN 3
#define PURPLE 4
#define GREEN 5
#define BLUE 6
#define YELLOW 7
#define ORANGE 8
#define BROWN 9
#define LTRED 10
#define DKGRAY 11
#define MDGRAY 12
#define LTGREEN 13
#define LTBLUE 14
#define LTGRAY 15

// ---------------------------------------------------------------------------
// Screen positions
// ---------------------------------------------------------------------------
#define COLS 40
#define ROWS 25

// ---------------------------------------------------------------------------
// Core screen utilities
// ---------------------------------------------------------------------------

void cls(void)
{
    vic.color_border = BLACK;
    vic.color_back = BLACK;
    for (int i = 0; i < 1000; i++)
    {
        SCREEN[i] = 32;
        COLORRAM[i] = BLACK;
    }
}

// Write zero-terminated screen-code string at absolute screen position
void pat(char row, char col, const char *s, char fg)
{
    int base = (int)row * COLS + col;
    while (*s)
    {
        SCREEN[base] = *s++;
        COLORRAM[base] = fg;
        base++;
    }
}

// Center a screen-code string on a row
void pcenter(char row, const char *s, char fg)
{
    char len = 0;
    const char *p = s;
    while (*p++)
        len++;
    pat(row, (COLS - len) >> 1, s, fg);
}

// Set color of an entire row without changing characters
void rowcol(char row, char fg)
{
    char *clr = COLORRAM + (int)row * COLS;
    for (char i = 0; i < COLS; i++)
        clr[i] = fg;
}

// Draw a horizontal line of one char across full width
void hline(char row, char ch, char fg)
{
    int base = (int)row * COLS + 2;
    for (char i = 0; i < 36; i++)
    {
        SCREEN[base + i] = ch;
        COLORRAM[base + i] = fg;
    }
}

// Put a single character at screen position
void pch(char row, char col, char ch, char fg)
{
    int pos = (int)row * COLS + col;
    SCREEN[pos] = ch;
    COLORRAM[pos] = fg;
}

// Read a single screen char
char gch(char row, char col)
{
    return SCREEN[(int)row * COLS + col];
}

// ---------------------------------------------------------------------------
// Frame sync (PAL 50Hz)
// ---------------------------------------------------------------------------

void wait_frame(void)
{
    while (vic.raster < 250)
        ;
    while (vic.raster >= 250)
        ;
}

void wait_frames(char n)
{
    while (n--)
        wait_frame();
}

// ---------------------------------------------------------------------------
// Input — Space, Return, F1, or Joystick 2 fire
// C64 keyboard matrix: PRA = column drive (active low), PRB = row read
//   Space:  col 7 (PRA=0x7F), row 4 (PRB bit 4)
//   Return: col 1 (PRA=0xFD), row 0 (PRB bit 0)
//   F1:     col 0 (PRA=0xFE), row 4 (PRB bit 4)
//   Joy2 fire: PRA bit 4 active low (with PRA=0xFF)
// ---------------------------------------------------------------------------

char any_key(void)
{
    // Space: col 7, row 4
    cia1.pra = 0x7F;
    if (!(cia1.prb & 0x10))
    {
        cia1.pra = 0xFF;
        return 1;
    }

    // Return: col 1, row 0
    cia1.pra = 0xFD;
    if (!(cia1.prb & 0x01))
    {
        cia1.pra = 0xFF;
        return 1;
    }

    // F1: col 0, row 4
    cia1.pra = 0xFE;
    if (!(cia1.prb & 0x10))
    {
        cia1.pra = 0xFF;
        return 1;
    }

    // Joystick 2 fire: PRA bit 4
    cia1.pra = 0xFF;
    if (!(cia1.pra & 0x10))
        return 1;

    return 0;
}

// Wait for key, debounced (wait for release then press)
void wait_key(void)
{
    // Wait for any previous press to be released
    while (any_key())
        wait_frame();
    // Now wait for a new press
    while (!any_key())
        wait_frame();
}

// ---------------------------------------------------------------------------
// Blink helper — call once per frame, returns 1 on the ON phase
// ---------------------------------------------------------------------------

static char blink_cnt = 0;
static char blink_phase = 0;

void blink_reset(void)
{
    blink_cnt = 0;
    blink_phase = 0;
}

char blink_step(void)
{
    if (++blink_cnt >= 25)
    {
        blink_cnt = 0;
        blink_phase = !blink_phase;
    }
    return blink_phase;
}

void blink_row(char row, char fg)
{
    rowcol(row, blink_step() ? fg : BLACK);
}

// ---------------------------------------------------------------------------
// Fade to black
// ---------------------------------------------------------------------------

void fade_to_black(void)
{
    for (char row = 0; row < 25; row++)
    {
        wait_frame();
        rowcol(row, BLACK);
    }
    vic.color_border = BLACK;
    vic.color_back = BLACK;
}

// ---------------------------------------------------------------------------
// Raster color bars (used in scenes 2, 3, 4)
// ---------------------------------------------------------------------------

#define NUM_BARS 8
#define BAR_HEIGHT 8

static char bar_pal[NUM_BARS] = {
    RED, ORANGE, YELLOW, WHITE, LTBLUE, BLUE, PURPLE, BLACK};

void bars_rotate(void)
{
    char tmp = bar_pal[0];
    for (char i = 0; i < NUM_BARS - 1; i++)
        bar_pal[i] = bar_pal[i + 1];
    bar_pal[NUM_BARS - 1] = tmp;
}

void bars_draw(char start_line)
{
    vic.color_border = BLACK;
    vic.color_back = BLACK;
    for (char b = 0; b < NUM_BARS; b++)
    {
        char target = start_line + (char)(b * BAR_HEIGHT);
        while (vic.raster != target)
            ;
        vic.color_border = bar_pal[b];
        vic.color_back = bar_pal[b];
    }
    char restore = start_line + (char)(NUM_BARS * BAR_HEIGHT);
    while (vic.raster != restore)
        ;
    vic.color_border = BLACK;
    vic.color_back = BLACK;
}

// ---------------------------------------------------------------------------
// Scrolling marquee — row 24
// 1 char every SCROLL_SPEED frames
// ---------------------------------------------------------------------------

#define SCROLL_SPEED 12

static const char scroll_text[] = {
    // WAR IS PEACE
    32, 32, 32, 23, 1, 18, 32, 9, 19, 32, 16, 5, 1, 3, 5, 32, 32, 32,
    // DISRUPTION IS PROGRESS
    4, 9, 19, 18, 21, 16, 20, 9, 15, 14, 32, 9, 19, 32, 16, 18, 15, 7, 18, 5, 19, 19, 32, 32, 32,
    // FREEDOM IS SLAVERY
    6, 18, 5, 5, 4, 15, 13, 32, 9, 19, 32, 19, 12, 1, 22, 5, 18, 25, 32, 32, 32,
    // YOUR DATA SETS YOU FREE
    25, 15, 21, 18, 32, 4, 1, 20, 1, 32, 19, 5, 20, 19, 32, 25, 15, 21, 32, 6, 18, 5, 5, 32, 32, 32,
    // IGNORANCE IS STRENGTH
    9, 7, 14, 15, 18, 1, 14, 3, 5, 32, 9, 19, 32, 19, 20, 18, 5, 14, 7, 20, 8, 32, 32, 32,
    // AI KNOWS BEST
    1, 9, 32, 11, 14, 15, 23, 19, 32, 2, 5, 19, 20, 32, 32, 32,
    // BIG BROTHER WATCHES
    2, 9, 7, 32, 2, 18, 15, 20, 8, 5, 18, 32, 23, 1, 20, 3, 8, 5, 19, 32, 32, 32,
    // ALEXA IS LISTENING
    1, 12, 5, 24, 1, 32, 9, 19, 32, 12, 9, 19, 20, 5, 14, 9, 14, 7, 32, 32, 32,
    // DID WE GET WHAT WE WERE PROMISED
    4, 9, 4, 32, 23, 5, 32, 7, 5, 20, 32, 23, 8, 1, 20, 32, 23, 5, 32, 23, 5, 18, 5, 32, 16, 18, 15, 13, 9, 19, 5, 4, 32, 32, 32,
    // AND AT WHAT COST
    1, 14, 4, 32, 1, 20, 32, 23, 8, 1, 20, 32, 3, 15, 19, 20, 32, 32, 32,
    0xFF};

static unsigned scroll_idx = 0;
static char scroll_buf[40];
static char scroll_tick = 0;

void scroll_init(void)
{
    scroll_idx = 0;
    scroll_tick = 0;
    for (char i = 0; i < 40; i++)
        scroll_buf[i] = 32;
}

void scroll_step(void)
{
    if (++scroll_tick < SCROLL_SPEED)
        return;
    scroll_tick = 0;
    for (char i = 0; i < 39; i++)
        scroll_buf[i] = scroll_buf[i + 1];
    char c = scroll_text[scroll_idx++];
    if (c == 0xFF)
    {
        scroll_idx = 0;
        c = scroll_text[0];
    }
    scroll_buf[39] = c;
    int base = 24 * COLS;
    for (char i = 0; i < 40; i++)
    {
        SCREEN[base + i] = scroll_buf[i];
        COLORRAM[base + i] = LTGREEN;
    }
}

// ===========================================================================
//
//  SCENE 1 — THE EYE
//
//  A hardware sprite eye, centered on screen.
//  Pupil animates: centre → right → centre → left → centre
//
//  Below: large block-letter "1984" (5 rows tall, screen code 160 = solid block)
//  Then: GEORGE ORWELL  and  PRESS FIRE TO CONTINUE
//
//  Sprite 0 is placed at screen centre, colour WHITE.
//  Sprite data is stored at $2000 (just above default screen area).
//
// ===========================================================================

// --- Sprite bitmaps (24x21 pixels, 63 bytes each) ---
// Generated from circular eye with hollow iris ring and solid pupil.

static const char eye_left[63] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 255, 0, 3, 255, 192, 15, 0, 240,
    30, 0, 120, 28, 0, 56,
    59, 192, 28, 63, 224, 28, 63, 224, 28, 63, 224, 28, 59, 192, 28,
    28, 0, 56, 30, 0, 120, 15, 0, 240, 3, 255, 192, 0, 255, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0};

static const char eye_centre[63] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 255, 0, 3, 255, 192, 15, 0, 240,
    30, 0, 120, 28, 0, 56,
    56, 60, 28, 56, 126, 28, 56, 126, 28, 56, 126, 28, 56, 60, 28,
    28, 0, 56, 30, 0, 120, 15, 0, 240, 3, 255, 192, 0, 255, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0};

static const char eye_right[63] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 255, 0, 3, 255, 192, 15, 0, 240,
    30, 0, 120, 28, 0, 56,
    56, 3, 220, 56, 7, 252, 56, 7, 252, 56, 7, 252, 56, 3, 220,
    28, 0, 56, 30, 0, 120, 15, 0, 240, 3, 255, 192, 0, 255, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0};

// ---------------------------------------------------------------------------
// Sprite hardware — raw VIC-II register writes
// VIC-II base: $D000
// $D000/$D001 = sprite 0 X/Y
// $D010       = sprite X MSBs
// $D015       = sprite enable
// $D01C       = sprite multicolor (0=single colour)
// $D01B       = sprite priority (0=in front of background)
// $D027       = sprite 0 colour
// Sprite pointer for sprite 0: screen_base + $3F8 = $07F8
// ---------------------------------------------------------------------------

#define VIC_SPR0_X (*((volatile char *)0xD000))
#define VIC_SPR0_Y (*((volatile char *)0xD001))
#define VIC_SPR_MSBX (*((volatile char *)0xD010))
#define VIC_SPR_ENA (*((volatile char *)0xD015))
#define VIC_SPR_MCOLOR (*((volatile char *)0xD01C))
#define VIC_SPR_PRIOR (*((volatile char *)0xD01B))
#define VIC_SPR_EXPX (*((volatile char *)0xD01D)) // X double size
#define VIC_SPR_EXPY (*((volatile char *)0xD017)) // Y double size
#define VIC_SPR0_COLOR (*((volatile char *)0xD027))
#define SPR_PTR0 (*((volatile char *)0x07F8))

// Sprite data at $2000 — block index = $2000/64 = 128
#define SPRITE_MEM ((char *)0x2000)
#define SPRITE_BLOCK 128

void sprite_load(const char *data)
{
    char *dst = SPRITE_MEM;
    for (char i = 0; i < 63; i++)
        dst[i] = data[i];
    dst[63] = 0;
}

void sprite_show(char x, char y, char color)
{
    SPR_PTR0 = SPRITE_BLOCK;
    VIC_SPR0_X = x;
    VIC_SPR0_Y = y;
    VIC_SPR_MSBX &= ~1;
    VIC_SPR0_COLOR = color;
    VIC_SPR_MCOLOR &= ~1; // single colour
    VIC_SPR_PRIOR &= ~1;  // in front of background
    VIC_SPR_EXPX |= 1;    // 2x width
    VIC_SPR_EXPY |= 1;    // 2x height
    VIC_SPR_ENA |= 1;     // enable
}

void sprite_hide(void)
{
    VIC_SPR_ENA &= ~1;
    VIC_SPR_EXPX &= ~1;
    VIC_SPR_EXPY &= ~1;
}

// --- Big block digit "1984" ---
// Screen code 160 = solid block, 32 = space
// Each digit is 3 wide x 5 tall, 2-space gap between digits
// Centered: start col 11, 5 rows starting at given screen row

#define BLK 160
#define SPC 32

// 5 rows of screen codes for "1984" (18 chars wide)
static const char year_row0[18] = {SPC, BLK, SPC, SPC, SPC, BLK, BLK, BLK, SPC, SPC, BLK, BLK, BLK, SPC, SPC, BLK, SPC, BLK};
static const char year_row1[18] = {BLK, BLK, SPC, SPC, SPC, BLK, SPC, BLK, SPC, SPC, BLK, SPC, BLK, SPC, SPC, BLK, SPC, BLK};
static const char year_row2[18] = {SPC, BLK, SPC, SPC, SPC, BLK, BLK, BLK, SPC, SPC, BLK, BLK, BLK, SPC, SPC, BLK, BLK, BLK};
static const char year_row3[18] = {SPC, BLK, SPC, SPC, SPC, SPC, SPC, BLK, SPC, SPC, BLK, SPC, BLK, SPC, SPC, SPC, SPC, BLK};
static const char year_row4[18] = {BLK, BLK, BLK, SPC, SPC, BLK, BLK, BLK, SPC, SPC, BLK, BLK, BLK, SPC, SPC, SPC, SPC, BLK};

void draw_year(char start_row, char color)
{
    const char *rows[5] = {year_row0, year_row1, year_row2, year_row3, year_row4};
    for (char r = 0; r < 5; r++)
    {
        int base = (int)(start_row + r) * COLS + 11;
        for (char c = 0; c < 18; c++)
        {
            SCREEN[base + c] = rows[r][c];
            COLORRAM[base + c] = color;
        }
    }
}

// Screen code strings
static const char s1_orwell[] = {7, 5, 15, 18, 7, 5, 32, 15, 18, 23, 5, 12, 12, 0}; // GEORGE ORWELL
static const char s1_press[] = {16, 18, 5, 19, 19, 32, 6, 9, 18, 5, 32, 20, 15, 32, 3, 15, 14, 20, 9, 14, 21, 5, 0};

void scene1_run(void)
{
    cls();
    cls();

    // --- Sprite eye, 2x expanded = 48x42 pixels ---
    // VIC sprite X: screen centre = pixel 160, plus VIC left border offset 24 = 184
    // At 2x, sprite is 48px wide so to centre: X = 184 - 24 = 160
    // VIC sprite Y: top of screen area = 50. We want eye in top quarter.
    // Y=50 puts the top of the 42px eye at the very top of the screen area.
    // Y=56 gives a small top margin — eye occupies roughly rows 1-6 of text.
    // Year is at row 12 (pixel 146) so there is plenty of gap.
    sprite_load(eye_centre);
    sprite_show(160, 56, WHITE);

    // --- Big year ---
    draw_year(12, WHITE);

    // --- Text ---
    hline(18, 45, DKGRAY);
    pcenter(20, s1_orwell, DKGRAY);
    pcenter(22, s1_press, MDGRAY);

    scroll_init();
    blink_reset();

    // Pupil sequence: centre(0) right(2) centre(0) left(1) centre(0)
    // Using 3 sprite frames: eye_left, eye_centre, eye_right
    // Sequence indices into that array, plus hold time in frames
    static const char seq_frame[5] = {1, 2, 1, 0, 1}; // 0=left 1=centre 2=right
    static const char seq_hold[5] = {60, 35, 25, 35, 60};
    char seq_idx = 0;
    char hold_cnt = 0;

    for (;;)
    {
        wait_frame();
        scroll_step();
        blink_row(22, MDGRAY);

        hold_cnt++;
        if (hold_cnt >= seq_hold[seq_idx])
        {
            hold_cnt = 0;
            seq_idx++;
            if (seq_idx >= 5)
                seq_idx = 0;

            // Load the right sprite frame
            char f = seq_frame[seq_idx];
            if (f == 0)
                sprite_load(eye_left);
            else if (f == 1)
                sprite_load(eye_centre);
            else
                sprite_load(eye_right);
        }

        if (any_key())
            break;
    }

    sprite_hide();
    wait_frames(5);
    fade_to_black();
    wait_frames(15);
}

// ===========================================================================
//
//  SCENE 2 — DOUBLETHINK / RASTER BANDS
//
//  Five colored raster bands paint the background behind each slogan pair.
//  The bands pulse via a sine-driven color table — alive, not static.
//
//  Structure:
//    Part 1 — Orwell's slogans appear one by one on colored bands (1984)
//    Part 2 — TV static glitch transition (crossing between worlds)
//    Part 3 — AI equivalents revealed on the same bands (NOW)
//    Part 4 — User input: "WHAT IS YOUR DREAM FOR TECHNOLOGY?"
//    Part 5 — Authorship statement typed out
//
//  Raster bands (PAL, raster line 51 = top of screen, 8 lines per text row):
//    Band 0: rows 2-3  -> rasters 67-83   (header)
//    Band 1: rows 5-6  -> rasters 91-107  (slogan pair 1)
//    Band 2: rows 8-9  -> rasters 115-131 (slogan pair 2)
//    Band 3: rows 11-12-> rasters 139-155 (slogan pair 3)
//    Band 4: rows 14-15-> rasters 163-179 (context label)
//
//  Keyboard input uses the KERNAL buffer ($C6 = count, $0277 = first key).
//  The KERNAL IRQ fills the buffer automatically — no matrix scanning needed.
//
// ===========================================================================

// Type out a string letter by letter at speed frames/char

// ===========================================================================
//
//  SCENE 2 — DOUBLETHINK
//
//  Three simultaneous sine-wave color scrollers:
//    Row 10: Orwell slogans      — red wave, right-to-left
//    Row 12: AI equivalents      — blue wave, left-to-right
//    Row 14: Timeline / context  — gray wave, right-to-left, slower
//
//  Color wave travels OPPOSITE to scroll direction on each row.
//  When the two main scrollers cross at centre, columns 16-23 flash white.
//
//  Structure:
//    Part 1 — Three scrollers run simultaneously. Fire to continue.
//    Part 2 — TV static glitch transition
//    Part 3 — User input: "WHAT IS YOUR DREAM FOR TECHNOLOGY?"
//    Part 4 — Authorship statement, ending on "WRITTEN BY THE FUTURE"
//
// ===========================================================================

// Color wave tables (16 entries, brightness cycles)
static const char wave_red[16] = {2, 2, 10, 10, 8, 8, 7, 1, 7, 7, 8, 8, 10, 2, 2, 11};
static const char wave_blue[16] = {6, 6, 14, 14, 3, 3, 1, 3, 3, 14, 14, 6, 4, 4, 6, 11};
static const char wave_gray[16] = {11, 11, 12, 12, 15, 15, 1, 15, 15, 12, 12, 11, 11, 0, 0, 11};

// Row 10: Orwell slogans, right-to-left
static const char smsg1[] = {
    32, 32, 32,
    23, 1, 18, 32, 9, 19, 32, 16, 5, 1, 3, 5, // WAR IS PEACE
    32, 32, 32,
    6, 18, 5, 5, 4, 15, 13, 32, 9, 19, 32, 19, 12, 1, 22, 5, 18, 25, // FREEDOM IS SLAVERY
    32, 32, 32,
    9, 7, 14, 15, 18, 1, 14, 3, 5, 32, 9, 19, 32, 19, 20, 18, 5, 14, 7, 20, 8, // IGNORANCE IS STRENGTH
    32, 32, 32,
    2, 9, 7, 32, 2, 18, 15, 20, 8, 5, 18, 32, 9, 19, 32, 23, 1, 20, 3, 8, 9, 14, 7, // BIG BROTHER IS WATCHING
    32, 32, 32,
    0xFF};

// Row 12: AI equivalents, left-to-right
// Message stored REVERSED so shift-right + feed-at-0 produces correct LTR display
static const char smsg2[] = {
    32, 32, 32,
    7, 14, 9, 14, 5, 20, 19, 9, 12, 32, 19, 9, 32, 1, 24, 5, 12, 1, // ALEXA IS LISTENING (reversed)
    32, 32, 32,
    20, 19, 5, 2, 32, 19, 23, 15, 14, 11, 32, 9, 1, // AI KNOWS BEST (reversed)
    32, 32, 32,
    25, 3, 14, 5, 18, 18, 21, 3, 32, 23, 5, 14, 32, 5, 8, 20, 32, 19, 9, 32, 1, 20, 1, 4, 32, 18, 21, 15, 25, // YOUR DATA... (reversed)
    32, 32, 32,
    5, 3, 1, 5, 16, 32, 19, 9, 32, 5, 3, 14, 1, 12, 12, 9, 5, 22, 18, 21, 19, // SURVEILLANCE IS PEACE (reversed)
    32, 32, 32,
    0xFF};

// Row 14: Timeline, right-to-left, slower
static const char smsg3[] = {
    32, 32, 32,
    49, 57, 52, 57, 32, 32,                                                             // 1949
    7, 5, 15, 18, 7, 5, 32, 15, 18, 23, 5, 12, 12, 32, 23, 1, 18, 14, 5, 4, 32, 21, 19, // GEORGE ORWELL WARNED US
    32, 32, 32,
    49, 57, 56, 52, 32, 32,                       // 1984
    4, 9, 4, 32, 23, 5, 32, 12, 9, 19, 20, 5, 14, // DID WE LISTEN
    32, 32, 32,
    50, 48, 50, 54, 32, 32,                                                         // 2026
    1, 18, 5, 32, 23, 5, 32, 19, 20, 9, 12, 12, 32, 12, 9, 19, 20, 5, 14, 9, 14, 7, // ARE WE STILL LISTENING
    32, 32, 32,
    0xFF};

// Scroller state struct
typedef struct
{
    char buf[40];
    unsigned msg_idx;
    char tick;
    char speed;
    char wave_phase;
    char direction; // 0=RTL  1=LTR
    char row;
    const char *wave;
    const char *msg;
} Scroller;

static Scroller scr[3];

void scroller_init(Scroller *s, char row, char speed, char dir,
                   const char *wave, const char *msg)
{
    s->row = row;
    s->speed = speed;
    s->direction = dir;
    s->wave = wave;
    s->msg = msg;
    s->msg_idx = 0;
    s->tick = 0;
    s->wave_phase = 0;
    for (char i = 0; i < 40; i++)
        s->buf[i] = 32;
}

void scroller_step(Scroller *s)
{
    s->tick++;
    if (s->tick >= s->speed)
    {
        s->tick = 0;
        char c = s->msg[s->msg_idx++];
        if (c == 0xFF)
        {
            s->msg_idx = 0;
            c = s->msg[0];
        }
        if (s->direction == 0)
        {
            // RTL: shift left, feed at right
            for (char i = 0; i < 39; i++)
                s->buf[i] = s->buf[i + 1];
            s->buf[39] = c;
        }
        else
        {
            // LTR: shift right, feed at left (message stored reversed)
            for (char i = 39; i > 0; i--)
                s->buf[i] = s->buf[i - 1];
            s->buf[0] = c;
        }
    }
    s->wave_phase = (s->wave_phase + 1) & 15;
    int base = (int)s->row * 40;
    // Both directions: buf maps directly to screen columns
    // Wave direction opposes scroll direction
    for (char i = 0; i < 40; i++)
    {
        SCREEN[base + i] = s->buf[i];
        char wi = (s->direction == 0) ? (s->wave_phase + i) & 15 : (s->wave_phase + (39 - i)) & 15;
        COLORRAM[base + i] = s->wave[wi];
    }
}

// Flash centre columns white when both main scrollers have content crossing
void scroller_crossflash(void)
{
    if (scr[0].buf[20] != 32 && scr[1].buf[19] != 32)
    {
        char *c0 = COLORRAM + (int)scr[0].row * 40;
        char *c1 = COLORRAM + (int)scr[1].row * 40;
        for (char i = 16; i < 24; i++)
        {
            c0[i] = WHITE;
            c1[i] = WHITE;
        }
    }
}

// TV static glitch
void glitch_transition(void)
{
    char lfsr = 0xACu;
    for (char pass = 0; pass < 18; pass++)
    {
        for (int i = 0; i < 1000; i++)
        {
            char bit = ((lfsr >> 7) ^ (lfsr >> 5) ^ (lfsr >> 4) ^ (lfsr >> 3)) & 1;
            lfsr = (lfsr << 1) | bit;
            SCREEN[i] = lfsr & 0x3F;
            COLORRAM[i] = (lfsr >> 4) & 0x0F;
        }
        wait_frame();
        wait_frame();
    }
    for (char row = 0; row < 25; row++)
    {
        char *c = COLORRAM + (int)row * 40;
        for (char i = 0; i < 40; i++)
            c[i] = BLACK;
        wait_frame();
    }
    cls();
}

// KERNAL keyboard buffer
#define KBUF_COUNT (*((volatile char *)0x00C6))
#define KBUF_START ((volatile char *)0x0277)

char read_key(void)
{
    if (!KBUF_COUNT)
        return 0;
    char k = KBUF_START[0];
    char cnt = KBUF_COUNT - 1;
    for (char i = 0; i < cnt; i++)
        KBUF_START[i] = KBUF_START[i + 1];
    KBUF_COUNT = cnt;
    return k;
}

char petscii_to_sc(char p)
{
    if (p >= 65 && p <= 90)
        return p - 64;
    if (p == 32 || p == 46 || p == 33 || p == 63 || p == 45)
        return p;
    if (p >= 48 && p <= 57)
        return p;
    return 0;
}

char input_line(char row, char col, char maxlen, char *buf, char fg)
{
    char len = 0, cur_tick = 0, cur_on = 1;
    for (char i = 0; i < maxlen + 1; i++)
        pch(row, col + i, 32, fg);
    for (;;)
    {
        wait_frame();
        if (++cur_tick >= 20)
        {
            cur_tick = 0;
            cur_on = !cur_on;
        }
        pch(row, col + len, cur_on ? 160 : 32, fg);
        char k = read_key();
        if (!k)
            continue;
        if (k == 13)
            break;
        if (k == 20)
        {
            if (len > 0)
            {
                pch(row, col + len, 32, fg);
                len--;
                pch(row, col + len, 32, fg);
                buf[len] = 0;
            }
            continue;
        }
        char sc = petscii_to_sc(k);
        if (sc && len < maxlen)
        {
            buf[len] = sc;
            pch(row, col + len, sc, fg);
            len++;
            pch(row, col + len, 32, fg);
        }
    }
    pch(row, col + len, 32, fg);
    buf[len] = 0;
    return len;
}

void typeout(char row, char col, const char *s, char fg, char speed)
{
    while (*s)
    {
        pch(row, col, *s, fg);
        s++;
        col++;
        wait_frames(speed);
        if (any_key())
            return;
    }
}

// Static strings
static const char s2_hdr[] = {49, 57, 56, 52, 32, 32, 22, 19, 32, 32, 14, 15, 23, 0}; // 1984  VS  NOW
static const char s2_l1[] = {15, 18, 23, 5, 12, 12, 0};                               // ORWELL
static const char s2_l2[] = {1, 9, 32, 13, 9, 18, 18, 15, 18, 0};                     // AI MIRROR
static const char s2_l3[] = {20, 9, 13, 5, 12, 9, 14, 5, 0};                          // TIMELINE
static const char s2_press[] = {16, 18, 5, 19, 19, 32, 6, 9, 18, 5, 32, 20, 15, 32, 3, 15, 14, 20, 9, 14, 21, 5, 0};
static const char s2_q[] = {23, 8, 1, 20, 32, 9, 19, 32, 25, 15, 21, 18, 32, 4, 18, 5, 1, 13, 32, 6, 15, 18, 32, 20, 5, 3, 8, 14, 15, 12, 15, 7, 25, 63, 0};
static const char s2_hint[] = {20, 25, 16, 5, 32, 25, 15, 21, 18, 32, 1, 14, 19, 23, 5, 18, 32, 32, 18, 5, 20, 21, 18, 14, 32, 20, 15, 32, 3, 15, 14, 6, 9, 18, 13, 0};
static const char s2_pfx[] = {62, 32, 0};
static const char s2_echo[] = {25, 15, 21, 18, 32, 4, 18, 5, 1, 13, 58, 0}; // YOUR DREAM:
// Authorship
static const char s2_by1[] = {20, 8, 9, 19, 32, 4, 5, 13, 15, 32, 23, 1, 19, 32, 13, 1, 4, 5, 32, 2, 25, 32, 1, 9, 0};
static const char s2_by2[] = {4, 9, 18, 5, 3, 20, 5, 4, 32, 2, 25, 32, 10, 15, 14, 1, 19, 32, 11, 10, 5, 12, 4, 13, 1, 14, 4, 0};
static const char s2_by3[] = {3, 15, 13, 13, 15, 4, 15, 18, 5, 32, 54, 52, 32, 32, 50, 48, 50, 54, 0};
static const char s2_m1[] = {20, 8, 5, 32, 13, 1, 3, 8, 9, 14, 5, 32, 20, 8, 1, 20, 32, 8, 5, 12, 4, 32, 20, 8, 5, 0};
static const char s2_m2[] = {6, 9, 18, 19, 20, 32, 16, 18, 15, 13, 9, 19, 5, 32, 14, 15, 23, 32, 18, 21, 14, 19, 32, 3, 15, 4, 5, 0};
static const char s2_m3[] = {23, 18, 9, 20, 20, 5, 14, 32, 2, 25, 32, 20, 8, 5, 32, 6, 21, 20, 21, 18, 5, 0};

// Building sentence words below separator
// Row 18: 1984 words  col 2: WAR . FREEDOM . STRENGTH . WATCHING
// Row 20: AI words    col 2: SURVEILLANCE . DATA . AI . LISTENING
static const char sw_war[] = {23, 1, 18, 0};
static const char sw_freedom[] = {6, 18, 5, 5, 4, 15, 13, 0};
static const char sw_strength[] = {19, 20, 18, 5, 14, 7, 20, 8, 0};
static const char sw_watching[] = {23, 1, 20, 3, 8, 9, 14, 7, 0};
static const char sw_surveillance[] = {19, 21, 18, 22, 5, 9, 12, 12, 1, 14, 3, 5, 0};
static const char sw_data[] = {4, 1, 20, 1, 0};
static const char sw_ai[] = {1, 9, 0};
static const char sw_listening[] = {12, 9, 19, 20, 5, 14, 9, 14, 7, 0};
static const char sw_dot[] = {32, 46, 32, 0}; // " . "

// Print word+dot at position, return new column
char reveal_word(char row, char col, const char *word, char fg)
{
    while (*word)
    {
        pch(row, col, *word, fg);
        col++;
        word++;
    }
    return col;
}

void scene2_run(void)
{
    // -----------------------------------------------------------------------
    // PART 1 — THREE SCROLLERS + BUILDING SENTENCE
    // -----------------------------------------------------------------------
    cls();
    cls();

    pcenter(1, s2_hdr, DKGRAY);
    hline(2, 45, DKGRAY);

    pat(10, 1, s2_l1, DKGRAY);
    pat(12, 1, s2_l2, DKGRAY);
    pat(14, 1, s2_l3, DKGRAY);

    hline(16, 45, DKGRAY);
    // No "press fire" — scene advances automatically after words are revealed

    // Slow speeds: 6 frames/char for main scrollers, 10 for timeline
    scroller_init(&scr[0], 10, 6, 0, wave_red, smsg1);
    scroller_init(&scr[1], 12, 6, 1, wave_blue, smsg2);
    scroller_init(&scr[2], 14, 10, 0, wave_gray, smsg3);

    blink_reset();

    char timer = 0;
    char words = 0;
    char col1 = 2;
    char col2 = 2;
    char hold_after_words = 0; // counts frames after all words revealed

    for (;;)
    {
        wait_frame();
        scroller_step(&scr[0]);
        scroller_step(&scr[1]);
        scroller_step(&scr[2]);
        scroller_crossflash();
        timer++;

        // Reveal word pairs below separator, staggered every 100 frames
        if (words < 4 && timer >= (char)(words * 100 + 80))
        {
            if (words == 0)
            {
                col1 = reveal_word(18, col1, sw_war, RED);
                col2 = reveal_word(20, col2, sw_surveillance, LTRED);
            }
            else if (words == 1)
            {
                col1 = reveal_word(18, col1, sw_dot, DKGRAY);
                col1 = reveal_word(18, col1, sw_freedom, CYAN);
                col2 = reveal_word(20, col2, sw_dot, DKGRAY);
                col2 = reveal_word(20, col2, sw_data, LTBLUE);
            }
            else if (words == 2)
            {
                col1 = reveal_word(18, col1, sw_dot, DKGRAY);
                col1 = reveal_word(18, col1, sw_strength, LTGREEN);
                col2 = reveal_word(20, col2, sw_dot, DKGRAY);
                col2 = reveal_word(20, col2, sw_ai, YELLOW);
            }
            else if (words == 3)
            {
                col1 = reveal_word(18, col1, sw_dot, DKGRAY);
                col1 = reveal_word(18, col1, sw_watching, ORANGE);
                col2 = reveal_word(20, col2, sw_dot, DKGRAY);
                col2 = reveal_word(20, col2, sw_listening, PURPLE);
            }
            words++;
        }

        // After all words revealed, hold for 150 frames (~3 sec) then auto-advance
        if (words >= 4)
        {
            hold_after_words++;
            if (hold_after_words >= 150)
                break;
        }
    }

    wait_frames(5);

    // -----------------------------------------------------------------------
    // PART 2 — GLITCH TRANSITION
    // -----------------------------------------------------------------------
    vic.color_border = BLACK;
    vic.color_back = BLACK;
    glitch_transition();
    wait_frames(10);

    // -----------------------------------------------------------------------
    // -----------------------------------------------------------------------
    // PART 3 — USER INPUT + DOUBLETHINK RESPONSE
    // User types their dream. Screen clears immediately to dots.
    // Column dissolve masks the "thinking" time.
    // Response comes back using their input — the magic moment.
    // -----------------------------------------------------------------------
    cls();
    cls();

    pcenter(8, s2_q, YELLOW);
    hline(10, 45, DKGRAY);
    pat(12, 1, s2_pfx, LTGRAY);
    pcenter(22, s2_hint, DKGRAY);

    static char input_buf[39];
    for (char i = 0; i < 39; i++)
        input_buf[i] = 32;
    char ilen = input_line(12, 3, 36, input_buf, WHITE);

    // Trim trailing spaces from input — find real length
    char rlen = ilen;
    while (rlen > 0 && input_buf[rlen - 1] == 32)
        rlen--;

    // Immediately clear everything — the machine takes over
    cls();
    cls();

    // Thinking dots — 3 dots pulse in centre while "processing"
    // 8 cycles = ~8 seconds of masking time for SML
    for (char cycle = 0; cycle < 8; cycle++)
    {
        pch(12, 18, 46, MDGRAY);
        wait_frames(12);
        pch(12, 20, 46, MDGRAY);
        wait_frames(12);
        pch(12, 22, 46, MDGRAY);
        wait_frames(20);
        pch(12, 18, 32, BLACK);
        pch(12, 20, 32, BLACK);
        pch(12, 22, 32, BLACK);
        wait_frames(10);
    }

    // Column dissolve — stride 7 through all 40 columns
    char dcol = 0;
    for (char step = 0; step < 40; step++)
    {
        for (char row = 0; row < 25; row++)
            COLORRAM[(int)row * 40 + dcol] = BLACK;
        dcol = (dcol + 7) % 40;
        wait_frame();
    }
    wait_frames(15);
    cls();
    cls();
    wait_frames(20);

    // --- THE RESPONSE ---
    // Keyword matching via responses.h (generated from responses.txt by convert.py)
    // To add/edit responses: edit responses.txt, run: python convert.py responses.txt responses.h
    // Phase 2: replace find_response() with SML serial call, keep display code identical.

    const char *match_l1;
    const char *match_l2;
    find_response(input_buf, rlen, &match_l1, &match_l2);

    // Static strings for response layout
    static const char r_hdr[] = {25, 15, 21, 32, 4, 18, 5, 1, 13, 5, 4, 32, 15, 6, 0};                                        // YOU DREAMED OF
    static const char r_sys[] = {20, 8, 5, 32, 19, 25, 19, 20, 5, 13, 32, 8, 5, 1, 18, 4, 0};                                 // THE SYSTEM HEARD
    static const char r_end[] = {25, 15, 21, 18, 32, 4, 18, 5, 1, 13, 32, 9, 19, 32, 20, 8, 5, 32, 19, 25, 19, 20, 5, 13, 0}; // YOUR DREAM IS THE SYSTEM

    // Reveal the response
    typeout(7, (40 - 14) >> 1, r_hdr, DKGRAY, 3);
    wait_frames(15);

    // Their exact words in white — this is the magic moment
    if (rlen > 0)
    {
        char icol = (40 - rlen) >> 1;
        for (char i = 0; i < rlen; i++)
        {
            SCREEN[8 * 40 + icol + i] = input_buf[i];
            COLORRAM[8 * 40 + icol + i] = WHITE;
        }
    }
    wait_frames(40);

    hline(10, 45, DKGRAY);
    wait_frames(20);

    typeout(12, (40 - 16) >> 1, r_sys, DKGRAY, 3);
    wait_frames(20);

    // Measure response lines for centering
    char l1len = 0;
    while (match_l1[l1len])
        l1len++;
    char l2len = 0;
    while (match_l2[l2len])
        l2len++;
    typeout(13, (40 - l1len) >> 1, match_l1, LTRED, 3);
    wait_frames(10);
    typeout(14, (40 - l2len) >> 1, match_l2, LTRED, 3);
    wait_frames(30);

    hline(16, 45, DKGRAY);
    wait_frames(30);

    typeout(18, (40 - 24) >> 1, r_end, MDGRAY, 4);

    wait_frames(120);
    fade_to_black();
    wait_frames(20);

    // -----------------------------------------------------------------------
    // PART 4 — AUTHORSHIP STATEMENT
    // Ends on "WRITTEN BY THE FUTURE" — scene 3 delivers the payoff
    // -----------------------------------------------------------------------
    cls();
    cls();

    wait_frames(30);
    typeout(6, (40 - 24) >> 1, s2_by1, LTGRAY, 2);
    wait_frames(15);
    typeout(8, (40 - 27) >> 1, s2_by2, WHITE, 2);
    wait_frames(15);
    typeout(10, (40 - 18) >> 1, s2_by3, DKGRAY, 2);
    wait_frames(30);
    hline(13, 45, DKGRAY);
    wait_frames(20);
    typeout(16, (40 - 25) >> 1, s2_m1, MDGRAY, 3);
    wait_frames(10);
    typeout(17, (40 - 27) >> 1, s2_m2, MDGRAY, 3);
    wait_frames(20);
    typeout(18, (40 - 21) >> 1, s2_m3, WHITE, 4);

    // Hold on the ambiguous line — blinking cursor implies incompleteness
    wait_frames(60);
    char cpos = ((40 - 21) >> 1) + 21;
    for (char b = 0; b < 10; b++)
    {
        pch(18, cpos, 160, WHITE);
        wait_frames(18);
        pch(18, cpos, 32, WHITE);
        wait_frames(18);
    }

    fade_to_black();
    wait_frames(20);
}

// ===========================================================================
//
//  SCENE 3 — THE QUESTION
//
//  Pure black. Two lines appear slowly. Raster bars in deep red.
//  No scroller. Just the question hanging in silence.
//
//  Row 10:  DID WE GET WHAT WE WERE PROMISED
//  Row 12:  OR SOMETHING FAR MORE DANGEROUS
//  Row 18:  PRESS FIRE TO CONTINUE
//
// ===========================================================================

static const char s3_q1[] = {
    4, 9, 4, 32, 23, 5, 32, 7, 5, 20, 32, 23, 8, 1, 20, 32, 23, 5, 32, 23, 5, 18, 5, 32, 16, 18, 15, 13, 9, 19, 5, 4, 0};
static const char s3_q2[] = {
    15, 18, 32, 19, 15, 13, 5, 20, 8, 9, 14, 7, 32, 6, 1, 18, 32, 13, 15, 18, 5, 46, 46, 46, 0};
// "OR SOMETHING FAR MORE..."  -- ends with ellipsis, color MDGRAY (neutral, neither hope nor warning)
// "THE END IS NOT YET WRITTEN"
static const char s3_end[] = {
    20, 8, 5, 32, 5, 14, 4, 32, 9, 19, 32, 14, 15, 20, 32, 25, 5, 20, 32, 23, 18, 9, 20, 20, 5, 14, 0};

void scene3_run(void)
{
    cls();

    wait_frames(40);
    pcenter(10, s3_q1, WHITE);
    wait_frames(50);
    pcenter(12, s3_q2, MDGRAY);
    wait_frames(40);

    // Show the final line and blink it — demo ends here
    pcenter(18, s3_end, MDGRAY);
    blink_reset();

    for (;;)
    {
        wait_frame();
        blink_row(18, WHITE);
        // Loop forever — this is the end
    }
}

// ===========================================================================
//
//  SCENE 4 — END SCREEN (loops)
//
//  Cool blue/purple bars. The final line blinks.
//
//  Row  8:  A C64 DEMO
//  Row 11:  [separator]
//  Row 13:  THE END IS NOT YET WRITTEN
//  Row 17:  [separator]
//  Row 20:  GEORGE ORWELL  1949
//  Row 24:  [scroller]
//
// ===========================================================================

// ===========================================================================
//  MAIN
// ===========================================================================

int main(void)
{
    vic.color_border = BLACK;
    vic.color_back = BLACK;

    scene1_run();
    scene2_run();
    scene3_run(); // loops forever — THE END IS NOT YET WRITTEN

    return 0;
}