// responses.h — AUTO-GENERATED by convert.py
// DO NOT EDIT — edit responses.txt and re-run convert.py
//
// 15 response entries + 1 default
// Generated from: responses.txt

// "HEALTH" -> "YOUR HEALTH DATA FEEDS THE MACHINE"
static const char _kw000[] = { 8,5,1,12,20,8, 0 };
static const char _r1_000[] = { 25,15,21,18,32,8,5,1,12,20,8,32,4,1,20,1,32,6,5,5,4,19,32,20,8,5,32,13,1,3,8,9,14,5, 0 };
static const char _r2_000[] = { 3,15,13,16,12,9,1,14,3,5,32,9,19,32,20,8,5,32,3,21,18,5, 0 };

// "PEACE" -> "PEACE REQUIRES TOTAL SURVEILLANCE"
static const char _kw001[] = { 16,5,1,3,5, 0 };
static const char _r1_001[] = { 16,5,1,3,5,32,18,5,17,21,9,18,5,19,32,20,15,20,1,12,32,19,21,18,22,5,9,12,12,1,14,3,5, 0 };
static const char _r2_001[] = { 25,15,21,18,32,19,1,6,5,20,25,32,9,19,32,15,21,18,32,16,18,15,4,21,3,20, 0 };

// "QUIET" -> "PEACE REQUIRES TOTAL SURVEILLANCE"
static const char _kw002[] = { 17,21,9,5,20, 0 };
static const char _r1_002[] = { 16,5,1,3,5,32,18,5,17,21,9,18,5,19,32,20,15,20,1,12,32,19,21,18,22,5,9,12,12,1,14,3,5, 0 };
static const char _r2_002[] = { 25,15,21,18,32,19,1,6,5,20,25,32,9,19,32,15,21,18,32,16,18,15,4,21,3,20, 0 };

// "HARMONY" -> "PEACE REQUIRES TOTAL SURVEILLANCE"
static const char _kw003[] = { 8,1,18,13,15,14,25, 0 };
static const char _r1_003[] = { 16,5,1,3,5,32,18,5,17,21,9,18,5,19,32,20,15,20,1,12,32,19,21,18,22,5,9,12,12,1,14,3,5, 0 };
static const char _r2_003[] = { 25,15,21,18,32,19,1,6,5,20,25,32,9,19,32,15,21,18,32,16,18,15,4,21,3,20, 0 };

// "FREEDOM" -> "FREEDOM IS MANAGED EFFICIENTLY"
static const char _kw004[] = { 6,18,5,5,4,15,13, 0 };
static const char _r1_004[] = { 6,18,5,5,4,15,13,32,9,19,32,13,1,14,1,7,5,4,32,5,6,6,9,3,9,5,14,20,12,25, 0 };
static const char _r2_004[] = { 23,9,20,8,9,14,32,1,16,16,18,15,22,5,4,32,16,1,18,1,13,5,20,5,18,19, 0 };

// "FREE" -> "FREEDOM IS MANAGED EFFICIENTLY"
static const char _kw005[] = { 6,18,5,5, 0 };
static const char _r1_005[] = { 6,18,5,5,4,15,13,32,9,19,32,13,1,14,1,7,5,4,32,5,6,6,9,3,9,5,14,20,12,25, 0 };
static const char _r2_005[] = { 23,9,20,8,9,14,32,1,16,16,18,15,22,5,4,32,16,1,18,1,13,5,20,5,18,19, 0 };

// "CONNECT" -> "CONNECTION IS WATCHED FOR YOUR GOOD"
static const char _kw006[] = { 3,15,14,14,5,3,20, 0 };
static const char _r1_006[] = { 3,15,14,14,5,3,20,9,15,14,32,9,19,32,23,1,20,3,8,5,4,32,6,15,18,32,25,15,21,18,32,7,15,15,4, 0 };
static const char _r2_006[] = { 9,19,15,12,1,20,9,15,14,32,16,18,15,20,5,3,20,19,32,20,8,5,32,19,25,19,20,5,13, 0 };

// "CONNECTION" -> "CONNECTION IS WATCHED FOR YOUR GOOD"
static const char _kw007[] = { 3,15,14,14,5,3,20,9,15,14, 0 };
static const char _r1_007[] = { 3,15,14,14,5,3,20,9,15,14,32,9,19,32,23,1,20,3,8,5,4,32,6,15,18,32,25,15,21,18,32,7,15,15,4, 0 };
static const char _r2_007[] = { 9,19,15,12,1,20,9,15,14,32,16,18,15,20,5,3,20,19,32,20,8,5,32,19,25,19,20,5,13, 0 };

// "LEARN" -> "LEARNING IS CURATED BY THE ALGORITHM"
static const char _kw008[] = { 12,5,1,18,14, 0 };
static const char _r1_008[] = { 12,5,1,18,14,9,14,7,32,9,19,32,3,21,18,1,20,5,4,32,2,25,32,20,8,5,32,1,12,7,15,18,9,20,8,13, 0 };
static const char _r2_008[] = { 25,15,21,18,32,3,21,18,9,15,19,9,20,25,32,9,19,32,15,21,18,32,4,1,20,1, 0 };

// "KNOWLEDGE" -> "LEARNING IS CURATED BY THE ALGORITHM"
static const char _kw009[] = { 11,14,15,23,12,5,4,7,5, 0 };
static const char _r1_009[] = { 12,5,1,18,14,9,14,7,32,9,19,32,3,21,18,1,20,5,4,32,2,25,32,20,8,5,32,1,12,7,15,18,9,20,8,13, 0 };
static const char _r2_009[] = { 25,15,21,18,32,3,21,18,9,15,19,9,20,25,32,9,19,32,15,21,18,32,4,1,20,1, 0 };

// "EDUCATION" -> "LEARNING IS CURATED BY THE ALGORITHM"
static const char _kw010[] = { 5,4,21,3,1,20,9,15,14, 0 };
static const char _r1_010[] = { 12,5,1,18,14,9,14,7,32,9,19,32,3,21,18,1,20,5,4,32,2,25,32,20,8,5,32,1,12,7,15,18,9,20,8,13, 0 };
static const char _r2_010[] = { 25,15,21,18,32,3,21,18,9,15,19,9,20,25,32,9,19,32,15,21,18,32,4,1,20,1, 0 };

// "CREATE" -> "CREATION REQUIRES A PERMIT"
static const char _kw011[] = { 3,18,5,1,20,5, 0 };
static const char _r1_011[] = { 3,18,5,1,20,9,15,14,32,18,5,17,21,9,18,5,19,32,1,32,16,5,18,13,9,20, 0 };
static const char _r2_011[] = { 25,15,21,18,32,9,4,5,1,19,32,2,5,12,15,14,7,32,20,15,32,20,8,5,32,3,12,15,21,4, 0 };

// "ART" -> "CREATION REQUIRES A PERMIT"
static const char _kw012[] = { 1,18,20, 0 };
static const char _r1_012[] = { 3,18,5,1,20,9,15,14,32,18,5,17,21,9,18,5,19,32,1,32,16,5,18,13,9,20, 0 };
static const char _r2_012[] = { 25,15,21,18,32,9,4,5,1,19,32,2,5,12,15,14,7,32,20,15,32,20,8,5,32,3,12,15,21,4, 0 };

// "MUSIC" -> "CREATION REQUIRES A PERMIT"
static const char _kw013[] = { 13,21,19,9,3, 0 };
static const char _r1_013[] = { 3,18,5,1,20,9,15,14,32,18,5,17,21,9,18,5,19,32,1,32,16,5,18,13,9,20, 0 };
static const char _r2_013[] = { 25,15,21,18,32,9,4,5,1,19,32,2,5,12,15,14,7,32,20,15,32,20,8,5,32,3,12,15,21,4, 0 };

// "WRITE" -> "CREATION REQUIRES A PERMIT"
static const char _kw014[] = { 23,18,9,20,5, 0 };
static const char _r1_014[] = { 3,18,5,1,20,9,15,14,32,18,5,17,21,9,18,5,19,32,1,32,16,5,18,13,9,20, 0 };
static const char _r2_014[] = { 25,15,21,18,32,9,4,5,1,19,32,2,5,12,15,14,7,32,20,15,32,20,8,5,32,3,12,15,21,4, 0 };

// "EQUAL" -> "EQUALITY IS ALGORITHMICALLY ASSIGNED"
static const char _kw015[] = { 5,17,21,1,12, 0 };
static const char _r1_015[] = { 5,17,21,1,12,9,20,25,32,9,19,32,1,12,7,15,18,9,20,8,13,9,3,1,12,12,25,32,1,19,19,9,7,14,5,4, 0 };
static const char _r2_015[] = { 25,15,21,18,32,19,3,15,18,5,32,8,1,19,32,2,5,5,14,32,14,15,20,5,4, 0 };

// "EQUALITY" -> "EQUALITY IS ALGORITHMICALLY ASSIGNED"
static const char _kw016[] = { 5,17,21,1,12,9,20,25, 0 };
static const char _r1_016[] = { 5,17,21,1,12,9,20,25,32,9,19,32,1,12,7,15,18,9,20,8,13,9,3,1,12,12,25,32,1,19,19,9,7,14,5,4, 0 };
static const char _r2_016[] = { 25,15,21,18,32,19,3,15,18,5,32,8,1,19,32,2,5,5,14,32,14,15,20,5,4, 0 };

// "FAIR" -> "EQUALITY IS ALGORITHMICALLY ASSIGNED"
static const char _kw017[] = { 6,1,9,18, 0 };
static const char _r1_017[] = { 5,17,21,1,12,9,20,25,32,9,19,32,1,12,7,15,18,9,20,8,13,9,3,1,12,12,25,32,1,19,19,9,7,14,5,4, 0 };
static const char _r2_017[] = { 25,15,21,18,32,19,3,15,18,5,32,8,1,19,32,2,5,5,14,32,14,15,20,5,4, 0 };

// "SAFE" -> "SAFETY REQUIRES FULL TRANSPARENCY"
static const char _kw018[] = { 19,1,6,5, 0 };
static const char _r1_018[] = { 19,1,6,5,20,25,32,18,5,17,21,9,18,5,19,32,6,21,12,12,32,20,18,1,14,19,16,1,18,5,14,3,25, 0 };
static const char _r2_018[] = { 25,15,21,18,32,12,15,3,1,20,9,15,14,32,8,1,19,32,2,5,5,14,32,12,15,7,7,5,4, 0 };

// "SECURITY" -> "SAFETY REQUIRES FULL TRANSPARENCY"
static const char _kw019[] = { 19,5,3,21,18,9,20,25, 0 };
static const char _r1_019[] = { 19,1,6,5,20,25,32,18,5,17,21,9,18,5,19,32,6,21,12,12,32,20,18,1,14,19,16,1,18,5,14,3,25, 0 };
static const char _r2_019[] = { 25,15,21,18,32,12,15,3,1,20,9,15,14,32,8,1,19,32,2,5,5,14,32,12,15,7,7,5,4, 0 };

// "PROTECT" -> "SAFETY REQUIRES FULL TRANSPARENCY"
static const char _kw020[] = { 16,18,15,20,5,3,20, 0 };
static const char _r1_020[] = { 19,1,6,5,20,25,32,18,5,17,21,9,18,5,19,32,6,21,12,12,32,20,18,1,14,19,16,1,18,5,14,3,25, 0 };
static const char _r2_020[] = { 25,15,21,18,32,12,15,3,1,20,9,15,14,32,8,1,19,32,2,5,5,14,32,12,15,7,7,5,4, 0 };

// "TRUTH" -> "TRUTH IS UPDATED IN REAL TIME"
static const char _kw021[] = { 20,18,21,20,8, 0 };
static const char _r1_021[] = { 20,18,21,20,8,32,9,19,32,21,16,4,1,20,5,4,32,9,14,32,18,5,1,12,32,20,9,13,5, 0 };
static const char _r2_021[] = { 25,5,19,20,5,18,4,1,25,19,32,22,5,18,19,9,15,14,32,9,19,32,4,5,12,5,20,5,4, 0 };

// "HONEST" -> "TRUTH IS UPDATED IN REAL TIME"
static const char _kw022[] = { 8,15,14,5,19,20, 0 };
static const char _r1_022[] = { 20,18,21,20,8,32,9,19,32,21,16,4,1,20,5,4,32,9,14,32,18,5,1,12,32,20,9,13,5, 0 };
static const char _r2_022[] = { 25,5,19,20,5,18,4,1,25,19,32,22,5,18,19,9,15,14,32,9,19,32,4,5,12,5,20,5,4, 0 };

// "TRUST" -> "TRUTH IS UPDATED IN REAL TIME"
static const char _kw023[] = { 20,18,21,19,20, 0 };
static const char _r1_023[] = { 20,18,21,20,8,32,9,19,32,21,16,4,1,20,5,4,32,9,14,32,18,5,1,12,32,20,9,13,5, 0 };
static const char _r2_023[] = { 25,5,19,20,5,18,4,1,25,19,32,22,5,18,19,9,15,14,32,9,19,32,4,5,12,5,20,5,4, 0 };

// "HUMAN" -> "HUMANITY IS BEING OPTIMISED"
static const char _kw024[] = { 8,21,13,1,14, 0 };
static const char _r1_024[] = { 8,21,13,1,14,9,20,25,32,9,19,32,2,5,9,14,7,32,15,16,20,9,13,9,19,5,4, 0 };
static const char _r2_024[] = { 25,15,21,18,32,21,16,7,18,1,4,5,32,9,19,32,19,3,8,5,4,21,12,5,4, 0 };

// "HUMANITY" -> "HUMANITY IS BEING OPTIMISED"
static const char _kw025[] = { 8,21,13,1,14,9,20,25, 0 };
static const char _r1_025[] = { 8,21,13,1,14,9,20,25,32,9,19,32,2,5,9,14,7,32,15,16,20,9,13,9,19,5,4, 0 };
static const char _r2_025[] = { 25,15,21,18,32,21,16,7,18,1,4,5,32,9,19,32,19,3,8,5,4,21,12,5,4, 0 };

// "PEOPLE" -> "HUMANITY IS BEING OPTIMISED"
static const char _kw026[] = { 16,5,15,16,12,5, 0 };
static const char _r1_026[] = { 8,21,13,1,14,9,20,25,32,9,19,32,2,5,9,14,7,32,15,16,20,9,13,9,19,5,4, 0 };
static const char _r2_026[] = { 25,15,21,18,32,21,16,7,18,1,4,5,32,9,19,32,19,3,8,5,4,21,12,5,4, 0 };

// "BETTER" -> "BETTER IS DEFINED BY THE SYSTEM"
static const char _kw027[] = { 2,5,20,20,5,18, 0 };
static const char _r1_027[] = { 2,5,20,20,5,18,32,9,19,32,4,5,6,9,14,5,4,32,2,25,32,20,8,5,32,19,25,19,20,5,13, 0 };
static const char _r2_027[] = { 25,15,21,18,32,2,1,19,5,12,9,14,5,32,8,1,19,32,2,5,5,14,32,19,5,20, 0 };

// "IMPROVE" -> "BETTER IS DEFINED BY THE SYSTEM"
static const char _kw028[] = { 9,13,16,18,15,22,5, 0 };
static const char _r1_028[] = { 2,5,20,20,5,18,32,9,19,32,4,5,6,9,14,5,4,32,2,25,32,20,8,5,32,19,25,19,20,5,13, 0 };
static const char _r2_028[] = { 25,15,21,18,32,2,1,19,5,12,9,14,5,32,8,1,19,32,2,5,5,14,32,19,5,20, 0 };

// "PROGRESS" -> "BETTER IS DEFINED BY THE SYSTEM"
static const char _kw029[] = { 16,18,15,7,18,5,19,19, 0 };
static const char _r1_029[] = { 2,5,20,20,5,18,32,9,19,32,4,5,6,9,14,5,4,32,2,25,32,20,8,5,32,19,25,19,20,5,13, 0 };
static const char _r2_029[] = { 25,15,21,18,32,2,1,19,5,12,9,14,5,32,8,1,19,32,2,5,5,14,32,19,5,20, 0 };

// "FUTURE" -> "THE FUTURE IS ALREADY ALLOCATED"
static const char _kw030[] = { 6,21,20,21,18,5, 0 };
static const char _r1_030[] = { 20,8,5,32,6,21,20,21,18,5,32,9,19,32,1,12,18,5,1,4,25,32,1,12,12,15,3,1,20,5,4, 0 };
static const char _r2_030[] = { 25,15,21,18,32,18,15,12,5,32,8,1,19,32,2,5,5,14,32,1,19,19,9,7,14,5,4, 0 };

// "TOMORROW" -> "THE FUTURE IS ALREADY ALLOCATED"
static const char _kw031[] = { 20,15,13,15,18,18,15,23, 0 };
static const char _r1_031[] = { 20,8,5,32,6,21,20,21,18,5,32,9,19,32,1,12,18,5,1,4,25,32,1,12,12,15,3,1,20,5,4, 0 };
static const char _r2_031[] = { 25,15,21,18,32,18,15,12,5,32,8,1,19,32,2,5,5,14,32,1,19,19,9,7,14,5,4, 0 };

// "HOPE" -> "THE FUTURE IS ALREADY ALLOCATED"
static const char _kw032[] = { 8,15,16,5, 0 };
static const char _r1_032[] = { 20,8,5,32,6,21,20,21,18,5,32,9,19,32,1,12,18,5,1,4,25,32,1,12,12,15,3,1,20,5,4, 0 };
static const char _r2_032[] = { 25,15,21,18,32,18,15,12,5,32,8,1,19,32,2,5,5,14,32,1,19,19,9,7,14,5,4, 0 };

// "WORK" -> "WORK IS AUTOMATED FOR YOUR FREEDOM"
static const char _kw033[] = { 23,15,18,11, 0 };
static const char _r1_033[] = { 23,15,18,11,32,9,19,32,1,21,20,15,13,1,20,5,4,32,6,15,18,32,25,15,21,18,32,6,18,5,5,4,15,13, 0 };
static const char _r2_033[] = { 25,15,21,18,32,18,5,4,21,14,4,1,14,3,25,32,9,19,32,1,16,16,18,15,22,5,4, 0 };

// "JOB" -> "WORK IS AUTOMATED FOR YOUR FREEDOM"
static const char _kw034[] = { 10,15,2, 0 };
static const char _r1_034[] = { 23,15,18,11,32,9,19,32,1,21,20,15,13,1,20,5,4,32,6,15,18,32,25,15,21,18,32,6,18,5,5,4,15,13, 0 };
static const char _r2_034[] = { 25,15,21,18,32,18,5,4,21,14,4,1,14,3,25,32,9,19,32,1,16,16,18,15,22,5,4, 0 };

// "EARN" -> "WORK IS AUTOMATED FOR YOUR FREEDOM"
static const char _kw035[] = { 5,1,18,14, 0 };
static const char _r1_035[] = { 23,15,18,11,32,9,19,32,1,21,20,15,13,1,20,5,4,32,6,15,18,32,25,15,21,18,32,6,18,5,5,4,15,13, 0 };
static const char _r2_035[] = { 25,15,21,18,32,18,5,4,21,14,4,1,14,3,25,32,9,19,32,1,16,16,18,15,22,5,4, 0 };

// "LOVE" -> "LOVE IS COMPATIBILITY SCORING"
static const char _kw036[] = { 12,15,22,5, 0 };
static const char _r1_036[] = { 12,15,22,5,32,9,19,32,3,15,13,16,1,20,9,2,9,12,9,20,25,32,19,3,15,18,9,14,7, 0 };
static const char _r2_036[] = { 25,15,21,18,32,13,1,20,3,8,32,8,1,19,32,2,5,5,14,32,15,16,20,9,13,9,19,5,4, 0 };

// "FAMILY" -> "LOVE IS COMPATIBILITY SCORING"
static const char _kw037[] = { 6,1,13,9,12,25, 0 };
static const char _r1_037[] = { 12,15,22,5,32,9,19,32,3,15,13,16,1,20,9,2,9,12,9,20,25,32,19,3,15,18,9,14,7, 0 };
static const char _r2_037[] = { 25,15,21,18,32,13,1,20,3,8,32,8,1,19,32,2,5,5,14,32,15,16,20,9,13,9,19,5,4, 0 };

// "TOGETHER" -> "LOVE IS COMPATIBILITY SCORING"
static const char _kw038[] = { 20,15,7,5,20,8,5,18, 0 };
static const char _r1_038[] = { 12,15,22,5,32,9,19,32,3,15,13,16,1,20,9,2,9,12,9,20,25,32,19,3,15,18,9,14,7, 0 };
static const char _r2_038[] = { 25,15,21,18,32,13,1,20,3,8,32,8,1,19,32,2,5,5,14,32,15,16,20,9,13,9,19,5,4, 0 };

// "THINK" -> "THINKING IS ASSISTED BY AI"
static const char _kw039[] = { 20,8,9,14,11, 0 };
static const char _r1_039[] = { 20,8,9,14,11,9,14,7,32,9,19,32,1,19,19,9,19,20,5,4,32,2,25,32,1,9, 0 };
static const char _r2_039[] = { 25,15,21,18,32,20,8,15,21,7,8,20,19,32,1,18,5,32,9,14,32,7,15,15,4,32,8,1,14,4,19, 0 };

// "MIND" -> "THINKING IS ASSISTED BY AI"
static const char _kw040[] = { 13,9,14,4, 0 };
static const char _r1_040[] = { 20,8,9,14,11,9,14,7,32,9,19,32,1,19,19,9,19,20,5,4,32,2,25,32,1,9, 0 };
static const char _r2_040[] = { 25,15,21,18,32,20,8,15,21,7,8,20,19,32,1,18,5,32,9,14,32,7,15,15,4,32,8,1,14,4,19, 0 };

// "IDEA" -> "THINKING IS ASSISTED BY AI"
static const char _kw041[] = { 9,4,5,1, 0 };
static const char _r1_041[] = { 20,8,9,14,11,9,14,7,32,9,19,32,1,19,19,9,19,20,5,4,32,2,25,32,1,9, 0 };
static const char _r2_041[] = { 25,15,21,18,32,20,8,15,21,7,8,20,19,32,1,18,5,32,9,14,32,7,15,15,4,32,8,1,14,4,19, 0 };

// DEFAULT: "YOUR DREAM HAS BEEN PROCESSED"
static const char _resp_default_1[] = { 25,15,21,18,32,4,18,5,1,13,32,8,1,19,32,2,5,5,14,32,16,18,15,3,5,19,19,5,4, 0 };
static const char _resp_default_2[] = { 1,14,4,32,13,15,14,5,20,9,19,5,4,32,1,3,3,15,18,4,9,14,7,12,25, 0 };

#define RESP_COUNT 42

static const char * const _kw_table[RESP_COUNT] = {
    _kw000, _kw001, _kw002, _kw003, _kw004, _kw005, _kw006, _kw007, _kw008, _kw009, _kw010, _kw011, _kw012, _kw013, _kw014, _kw015, _kw016, _kw017, _kw018, _kw019, _kw020, _kw021, _kw022, _kw023, _kw024, _kw025, _kw026, _kw027, _kw028, _kw029, _kw030, _kw031, _kw032, _kw033, _kw034, _kw035, _kw036, _kw037, _kw038, _kw039, _kw040, _kw041
};

static const char * const _r1_table[RESP_COUNT] = {
    _r1_000, _r1_001, _r1_002, _r1_003, _r1_004, _r1_005, _r1_006, _r1_007, _r1_008, _r1_009, _r1_010, _r1_011, _r1_012, _r1_013, _r1_014, _r1_015, _r1_016, _r1_017, _r1_018, _r1_019, _r1_020, _r1_021, _r1_022, _r1_023, _r1_024, _r1_025, _r1_026, _r1_027, _r1_028, _r1_029, _r1_030, _r1_031, _r1_032, _r1_033, _r1_034, _r1_035, _r1_036, _r1_037, _r1_038, _r1_039, _r1_040, _r1_041
};

static const char * const _r2_table[RESP_COUNT] = {
    _r2_000, _r2_001, _r2_002, _r2_003, _r2_004, _r2_005, _r2_006, _r2_007, _r2_008, _r2_009, _r2_010, _r2_011, _r2_012, _r2_013, _r2_014, _r2_015, _r2_016, _r2_017, _r2_018, _r2_019, _r2_020, _r2_021, _r2_022, _r2_023, _r2_024, _r2_025, _r2_026, _r2_027, _r2_028, _r2_029, _r2_030, _r2_031, _r2_032, _r2_033, _r2_034, _r2_035, _r2_036, _r2_037, _r2_038, _r2_039, _r2_040, _r2_041
};

// find_response: scan input (screen codes) for first matching keyword.
// Sets *out_l1 and *out_l2 to the matched response lines.
// input: screen-code buffer, ilen: actual typed length (no trailing spaces)
void find_response(const char *input, char ilen,
                   const char **out_l1, const char **out_l2)
{
    for (char k = 0; k < RESP_COUNT; k++)
    {
        const char *kw = _kw_table[k];
        char kwlen = 0;
        while (kw[kwlen]) kwlen++;
        if (kwlen > ilen) continue;

        for (char i = 0; i + kwlen <= ilen; i++)
        {
            char match = 1;
            for (char j = 0; j < kwlen; j++)
            {
                if (input[i+j] != kw[j]) { match = 0; break; }
            }
            if (match)
            {
                *out_l1 = _r1_table[k];
                *out_l2 = _r2_table[k];
                return;
            }
        }
    }
    // No match — use default
    *out_l1 = _resp_default_1;
    *out_l2 = _resp_default_2;
}
